// <auto-generated />
using System;
using BoletosWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoletosWeb.Migrations
{
    [DbContext(typeof(BoletosWebContext))]
    [Migration("20220901235344_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoletosWeb.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("BoletosWeb.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUF")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("BoletosWeb.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdMoradorId")
                        .HasColumnType("int");

                    b.Property<int?>("IdProprietarioId")
                        .HasColumnType("int");

                    b.Property<string>("codImovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("dimensao")
                        .HasColumnType("float");

                    b.Property<int>("numGaragem")
                        .HasColumnType("int");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.Property<double>("vrDevido")
                        .HasColumnType("float");

                    b.Property<double>("vrExtra")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdMoradorId");

                    b.HasIndex("IdProprietarioId");

                    b.ToTable("Imovel");
                });

            modelBuilder.Entity("BoletosWeb.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pessoa");
                });

            modelBuilder.Entity("BoletosWeb.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("BoletosWeb.Models.Pessoa_Fisica", b =>
                {
                    b.HasBaseType("BoletosWeb.Models.Pessoa");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Pessoa_Fisica");
                });

            modelBuilder.Entity("BoletosWeb.Models.Pessoa_Juridica", b =>
                {
                    b.HasBaseType("BoletosWeb.Models.Pessoa");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Pessoa_Juridica");
                });

            modelBuilder.Entity("BoletosWeb.Models.Endereco", b =>
                {
                    b.HasOne("BoletosWeb.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("BoletosWeb.Models.Imovel", b =>
                {
                    b.HasOne("BoletosWeb.Models.Pessoa", "IdMorador")
                        .WithMany()
                        .HasForeignKey("IdMoradorId");

                    b.HasOne("BoletosWeb.Models.Pessoa", "IdProprietario")
                        .WithMany()
                        .HasForeignKey("IdProprietarioId");

                    b.Navigation("IdMorador");

                    b.Navigation("IdProprietario");
                });

            modelBuilder.Entity("BoletosWeb.Models.Telefone", b =>
                {
                    b.HasOne("BoletosWeb.Models.Pessoa", "Pessoa")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("BoletosWeb.Models.Pessoa", b =>
                {
                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
